export const FORM_UNIFIED_VARIANT = {
  TEXT: "TEXT",
  SEARCH: "SEARCH",
  NUMBER: "NUMBER",
  TEXTAREA: "TEXTAREA",
  CHECKBOX: "CHECKBOX",
  SWITCH: "SWITCH",
  SWITCH_ONOFF: "SWITCH_ONOFF",
  RADIO_GROUP: "RADIO_GROUP",
  SELECT: "SELECT",
  SELECT_INFINITE: "SELECT_INFINITE",
  UID: "UID",
  RICH_EDITOR: "RICH_EDITOR",
  DATE_PICKER: "DATE_PICKER",
  SLIDER: "SLIDER"
} as const
